# Generated by Django 5.1 on 2024-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
