# Generated by Django 5.1 on 2024-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_delete_project_alter_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.BooleanField(default=False),
        ),
    ]
