# Generated by Django 5.1 on 2024-10-17 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_oders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="oders",
            old_name="profile",
            new_name="user",
        ),
    ]
