# Generated by Django 5.1 on 2024-10-17 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_profile_oders_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Oders",
            new_name="Orders",
        ),
        migrations.AlterModelTable(
            name="orders",
            table="orders",
        ),
    ]
